services:
  postfix:
    build: ./postfix
    container_name: postfix
    env_file:
      - path: ".env"
        required: true
    ports:
      - "${POSTFIX_PORT}:${POSTFIX_PORT}"
    volumes:
      - ./maildata:/home/mailuser
    restart: unless-stopped

  api:
    build: ./api
    container_name: api
    env_file:
      - path: ".env"
        required: true
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./maildata:/home/mailuser
