services:
  postfix:
    build: ./postfix
    container_name: postfix
    ports:
      - "25:25"
    volumes:
      - ./maildata:/home/mailuser
    restart: unless-stopped
    environment:
      - MAILNAME=mail.mailfluence.top

  api:
    build: ./api
    container_name: api
    command: pnpm start
    ports:
      - "3000:3000"
    volumes:
      - ./maildata:/home/mailuser